### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by quangv** [stefanpenner/fs-tree-diff#32]
```

quang@debian:~/dev/project/client$ ember --version
Unexpected reserved word
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/quang/dev/org/client/node_modules/ember-cli-sass/node_modules/broccoli-merge-trees/node_modules/fs-tree-diff/lib/index.js:4:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

```

While trying to fix this error https://github.com/aexmachina/ember-cli-sass/issues/128 ... using this branch https://github.com/heimdalljs/heimdalljs-lib/tree/gentler-version-checking ...

might be an error that hasn't occurred yet? Because heimdalljs hasn't merged branch _gentler-version-checking_ yet.

**Comment by stefanpenner** [comment]
cc @hjdivad

**Comment by hjdivad** [comment]
@quangv thanks for the report.  I think you may have been using a version on that branch in which the build step wasn't quite right.

Do you still see this behaviour against `v0.1.5` of heimdalljs?

**Comment by quangv** [comment]
sorry, probably good to disregard... I was using `heimdalljs-lib` as `heimdalljs-logger` (manually installed it in the `fs-tree-diff` node_modules directory.

I was trying to trouble-shoot this: https://github.com/aexmachina/ember-cli-sass/issues/128 which has be resolved.
